[workspace]
resolver = "2"
members = [ "clients/cli",
    "uv-core",
    "uv-service",

    "clients/cli",

    "prisms/aws/curl",
    "prisms/aws/ada",
    "prisms/aws/burner",
    "prisms/aws/accounts",
    "prisms/core/bedrock",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
