[workspace]
resolver = "2"
members = [
    "blue-core",
    "blue-core-ai",
    "blue-ai",
    "blue-ada",
    "blue-cli",
    "blue-render-core",
    "blue-render-cli",
    "blue-core-cmd",
    "blue-cmd",
    "blue-core-process",
    "blue-process",
    "blue-download",
    "blue-system"
, "blue-module-runner", "blue-core-download"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
thiserror = "1.0"
blue-core = { path = "blue-core" }
blue-render-core = { path = "blue-render-core" }
blue-render-cli = { path = "blue-render-cli" }
