[module]
name = "core-cmd"
version = "1.0.0"
namespace = "blue"
description = "Core command execution functionality"

[[methods]]
path = ["exec"]
description = "Execute a command or script"
args_schema = """
{
    "type": "object",
    "properties": {
        "command": {
            "type": "string",
            "description": "Command to execute"
        },
        "shell": {
            "type": "string",
            "description": "Shell to use (defaults to current shell)",
            "enum": ["bash", "sh", "zsh"]
        },
        "env": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            },
            "description": "Environment variables"
        },
        "cwd": {
            "type": "string",
            "description": "Working directory"
        }
    },
    "required": ["command"]
}
"""
return_schema = """
{
    "type": "object",
    "properties": {
        "stdout": {
            "type": "string",
            "description": "Command standard output"
        },
        "stderr": {
            "type": "string",
            "description": "Command standard error"
        },
        "status": {
            "type": "number",
            "description": "Exit status code"
        }
    }
}
"""
display = """{ 
    "type": "stream",
    "stderr_prefix": null,
    "color_stderr": false,
    "fallback": { "type": "raw" }
}"""
