[module]
name = "process"
version = "1.0.0"
namespace = "blue"
description = "User-friendly process management"

[[methods]]
path = ["list"]
description = "List processes"
args_schema = '''
{
  "type": "object",
  "properties": {
    "filter": {
      "type": "string",
      "description": "Filter by command name"
    },
    "status": {
      "type": "string",
      "enum": ["running", "exited", "all"],
      "default": "all",
      "description": "Filter by process status"
    }
  }
}
'''
display = '''{ 
  "type": "table",
  "source": "processes",
  "columns": [
    {
      "title": "ID",
      "value": "short_id",
      "max_width": 8
    },
    {
      "title": "PID",
      "value": "pid",
      "align": "right"
    },
    {
      "title": "Status",
      "value": "status",
      "color": {
        "Running": "green",
        "Success": "cyan",
        "Failed": "red"
      }
    },
    {
      "title": "Started",
      "value": "relative_time"
    },
    {
      "title": "Command",
      "value": "command",
      "max_width": 50
    }
  ]
}'''

[[methods]]
path = ["start"]
description = "Start a new process"
args_schema = '''
{
  "type": "object",
  "properties": {
    "command": {
      "type": "string",
      "description": "Command to execute"
    },
    "args": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Command arguments"
    },
    "cwd": {
      "type": "string",
      "description": "Working directory"
    },
        "evars": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^[^=]+=.+$"
            },
            "description": "Environment variables in KEY=VALUE format"
    }
  },
  "required": ["command"]
}
'''

[[methods]]
path = ["stop"]
description = "Stop one or more processes"
args_schema = '''
{
  "type": "object",
  "properties": {
    "ids": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Process IDs (or prefixes) to stop"
    },
    "filter": {
      "type": "string",
      "description": "Stop processes matching command pattern"
    },
    "running": {
      "type": "boolean",
      "description": "Stop all running processes",
      "default": false
    },
    "force": {
      "type": "boolean",
      "description": "Force stop immediately",
      "default": false
    }
  },
  "oneOf": [
    { "required": ["ids"] },
    { "required": ["filter"] },
    { "required": ["running"] }
  ]
}
'''

[[methods]]
path = ["logs"]
description = "Show process logs"
args_schema = '''
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Process ID (prefix)"
    },
    "follow": {
      "type": "boolean",
      "description": "Follow log output (Ctrl-C to stop)",
      "default": false
    },
    "tail": {
      "type": "integer",
      "description": "Number of lines to show",
      "default": 100
    },
    "timestamps": {
      "type": "boolean",
      "description": "Show timestamps",
      "default": false
    },
    "stream": {
      "type": "string",
      "enum": ["stdout", "stderr", "both"],
      "default": "both",
      "description": "Which stream to follow"
    }
  },
  "required": ["id"]
}
'''
display = '''{ 
  "type": "text",
  "source": ["stdout", "stderr"],
  "join": "\\n"
}'''
