[package]
name = "uv-ui"
version = "0.1.0"
edition = "2021"
description = "Abstract UI component system for Ultraviolet"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
url = "2.4"
thiserror = "1.0"
