[module]
name = "ai"
version = "1.0.0"
namespace = "blue"
description = "AI assistant with streaming output and web interface"

[[methods]]
path = ["web"]
description = "Start a web server for AI interaction through a browser interface"
args_schema = '''
{
  "type": "object",
  "properties": {
    "port": {
      "type": "number",
      "description": "Port to run the web server on",
      "default": 3000
    },
    "host": {
      "type": "string",
      "description": "Host address to bind to",
      "default": "127.0.0.1"
    }
  }
}
'''

[[methods]]
path = ["ask"]
description = "Send a prompt to Claude AI with streaming output"
args_schema = '''
{
  "type": "object",
  "properties": {
    "prompt": {
      "type": "string",
      "description": "The prompt to send to Claude"
    },
    "files": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "Path to a file to include as context"
      }
    }
  },
  "required": ["prompt"]
}
'''
display = """{ "type": "stream" }"""
