[package]
name = "blue-render-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
blue-render-core = { path = "../blue-render-core" }
serde_json = "1.0"
anyhow = "1.0"
ansi_term = "0.12"
terminal-link = "0.1"
