[module]
name = "download"
version = "1.0.0"
namespace = "blue"
description = "Download manager for URLs"

[[methods]]
path = ["start"]
description = "Start a download from a URL"
args_schema = """
{
    "type": "object",
    "properties": {
        "url": {
            "type": "string",
            "description": "URL to download"
        },
        "output_dir": {
            "type": "string",
            "description": "Directory to save download to",
            "default": "~/Downloads"
        }
    },
    "required": ["url"]
}
"""
return_schema = """
{
    "type": "object",
    "properties": {
        "downloads": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": { "type": "string" },
                    "url": { "type": "string" },
                    "status": { "type": "string" },
                    "progress": { "type": "string" },
                    "speed": { "type": "string" },
                    "eta": { "type": "string" }
                }
            }
        }
    }
}
"""
display = """
{
    "type": "table",
    "source": "downloads",
    "columns": [
        { "title": "ID", "value": "id", "width": 8 },
        { "title": "URL", "value": "url", "width": 40 },
        { "title": "Status", "value": "status", "width": 10 },
        { "title": "Progress", "value": "progress", "width": 10 },
        { "title": "Speed", "value": "speed", "width": 10 },
        { "title": "ETA", "value": "eta", "width": 10 }
    ]
}
"""

[[methods]]
path = ["list"]
description = "List all downloads"
args_schema = """
{
    "type": "object",
    "properties": {}
}
"""
return_schema = """
{
    "type": "object",
    "properties": {
        "downloads": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": { "type": "string" },
                    "url": { "type": "string" },
                    "status": { "type": "string" },
                    "progress": { "type": "string" },
                    "speed": { "type": "string" },
                    "eta": { "type": "string" }
                }
            }
        }
    }
}
"""
display = """
{
    "type": "table",
    "source": "downloads",
    "columns": [
        { "title": "ID", "value": "id", "width": 8 },
        { "title": "URL", "value": "url", "width": 40 },
        { "title": "Status", "value": "status", "width": 10 },
        { "title": "Progress", "value": "progress", "width": 10 },
        { "title": "Speed", "value": "speed", "width": 10 },
        { "title": "ETA", "value": "eta", "width": 10 }
    ]
}
"""

[[methods]]
path = ["get"]
description = "Download a file with progress tracking"
args_schema = """
{
    "type": "object",
    "properties": {
        "url": {
            "type": "string",
            "description": "URL to download"
        },
        "output_dir": {
            "type": "string",
            "description": "Directory to save download to",
            "default": "."
        }
    },
    "required": ["url"]
}
"""
