[package]
name = "blue-module-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
blue-core = { path = "../blue-core" }
clap = { version = "4.0", features = ["derive"] }
serde_json = { workspace = true }
libloading = "0.8"
